# == Class: mcollective::facts
#
# Class that manages the facts file creation from the data generated by Puppet
#
# === Parameters
#  $mco_etc
#     This is used to pass over the standard mcollective directory path
#
# === Variables
#
# === Examples
#
#  class { mcollective::facts
#  }
#
# === Authors
#
# Jonathan Shanks <jon.shanks@gmail.com>
#
# === Copyright
#
# Copyright 2013 Jon Shanks
#
class mcollective::facts($mco_etc = '/etc/puppetlabs/mcollective')
{

  file { "${mco_etc}/facts.yaml":
    owner   => 'root',
    group   => 'root',
    mode    => '0400',
    content =>  template('mcollective/facts.yaml.erb'),
  }

}
